# Generated by Django 3.2 on 2021-04-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], max_length=50),
        ),
    ]
